# Generated by Django 5.2.10 on 2026-02-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="The ID from the source CSV or POS system",
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total Profit"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Star", "Star"),
                    ("Plowhorse", "Plowhorse"),
                    ("Puzzle", "Puzzle"),
                    ("Dog", "Dog"),
                ],
                help_text="AI-generated menu engineering category",
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Actual cost to prepare this item",
                max_digits=10,
                verbose_name="Cost",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_active"], name="menu_menuit_categor_ed013e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["external_id"], name="menu_menuit_externa_831b9a_idx"
            ),
        ),
    ]
