# Generated by Django 5.2.10 on 2026-02-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_order_created_at"),
        ("menu", "0002_menuitem_external_id_menuitem_total_profit_and_more"),
    ]

    operations = []
