# Generated by Django 5.2.10 on 2026-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_merge_20260207_0758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="total_purchases",
            field=models.FloatField(default=0, verbose_name="Total Purchases"),
        ),
    ]
