# Generated by Django 5.2.10 on 2026-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_menuitem_total_purchases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Total Profit"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="total_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Total Revenue"
            ),
        ),
    ]
