# Generated by Django 5.2.10 on 2026-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_menuitem_total_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Actual cost to prepare this item",
                max_digits=20,
                verbose_name="Cost",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Tax"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_at_order",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price captured at time of order",
                max_digits=20,
                verbose_name="Price at Order",
            ),
        ),
    ]
